<?xml version="1.0" encoding="utf-8"?><Database Name="SmartPhoneDB" Class="SmartPhoneDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MAYTINH;Initial Catalog=SmartPhoneDB;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="SmartPhoneLINQ.Properties.Settings" SettingsPropertyName="SmartPhoneDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SmartPhone" Member="SmartPhones">
    <Type Name="SmartPhone">
      <Column Name="SmartPhoneID" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[SmartPhone Name]" Member="SmartPhone_Name" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[Smart Phone Type]" Member="Smart_Phone_Type" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="[Announced Date]" Member="Announced_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Platform" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Camera" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="RAM" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Battery" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImageName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
</Database>