#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartPhoneLINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SmartPhoneDB")]
	public partial class SmartPhoneDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSmartPhone(SmartPhone instance);
    partial void UpdateSmartPhone(SmartPhone instance);
    partial void DeleteSmartPhone(SmartPhone instance);
    #endregion
		
		public SmartPhoneDBDataContext() : 
				base(global::SmartPhoneLINQ.Properties.Settings.Default.SmartPhoneDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SmartPhoneDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SmartPhoneDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SmartPhoneDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SmartPhoneDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SmartPhone> SmartPhones
		{
			get
			{
				return this.GetTable<SmartPhone>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SmartPhone")]
	public partial class SmartPhone : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SmartPhoneID;
		
		private string _SmartPhone_Name;
		
		private string _Smart_Phone_Type;
		
		private System.Nullable<System.DateTime> _Announced_Date;
		
		private string _Platform;
		
		private string _Camera;
		
		private string _RAM;
		
		private string _Battery;
		
		private System.Nullable<int> _Price;
		
		private string _ImageName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSmartPhoneIDChanging(string value);
    partial void OnSmartPhoneIDChanged();
    partial void OnSmartPhone_NameChanging(string value);
    partial void OnSmartPhone_NameChanged();
    partial void OnSmart_Phone_TypeChanging(string value);
    partial void OnSmart_Phone_TypeChanged();
    partial void OnAnnounced_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnAnnounced_DateChanged();
    partial void OnPlatformChanging(string value);
    partial void OnPlatformChanged();
    partial void OnCameraChanging(string value);
    partial void OnCameraChanged();
    partial void OnRAMChanging(string value);
    partial void OnRAMChanged();
    partial void OnBatteryChanging(string value);
    partial void OnBatteryChanged();
    partial void OnPriceChanging(System.Nullable<int> value);
    partial void OnPriceChanged();
    partial void OnImageNameChanging(string value);
    partial void OnImageNameChanged();
    #endregion
		
		public SmartPhone()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmartPhoneID", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SmartPhoneID
		{
			get
			{
				return this._SmartPhoneID;
			}
			set
			{
				if ((this._SmartPhoneID != value))
				{
					this.OnSmartPhoneIDChanging(value);
					this.SendPropertyChanging();
					this._SmartPhoneID = value;
					this.SendPropertyChanged("SmartPhoneID");
					this.OnSmartPhoneIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SmartPhone Name]", Storage="_SmartPhone_Name", DbType="NVarChar(30)")]
		public string SmartPhone_Name
		{
			get
			{
				return this._SmartPhone_Name;
			}
			set
			{
				if ((this._SmartPhone_Name != value))
				{
					this.OnSmartPhone_NameChanging(value);
					this.SendPropertyChanging();
					this._SmartPhone_Name = value;
					this.SendPropertyChanged("SmartPhone_Name");
					this.OnSmartPhone_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Smart Phone Type]", Storage="_Smart_Phone_Type", DbType="NVarChar(20)")]
		public string Smart_Phone_Type
		{
			get
			{
				return this._Smart_Phone_Type;
			}
			set
			{
				if ((this._Smart_Phone_Type != value))
				{
					this.OnSmart_Phone_TypeChanging(value);
					this.SendPropertyChanging();
					this._Smart_Phone_Type = value;
					this.SendPropertyChanged("Smart_Phone_Type");
					this.OnSmart_Phone_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Announced Date]", Storage="_Announced_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Announced_Date
		{
			get
			{
				return this._Announced_Date;
			}
			set
			{
				if ((this._Announced_Date != value))
				{
					this.OnAnnounced_DateChanging(value);
					this.SendPropertyChanging();
					this._Announced_Date = value;
					this.SendPropertyChanged("Announced_Date");
					this.OnAnnounced_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Platform", DbType="NVarChar(30)")]
		public string Platform
		{
			get
			{
				return this._Platform;
			}
			set
			{
				if ((this._Platform != value))
				{
					this.OnPlatformChanging(value);
					this.SendPropertyChanging();
					this._Platform = value;
					this.SendPropertyChanged("Platform");
					this.OnPlatformChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Camera", DbType="NVarChar(20)")]
		public string Camera
		{
			get
			{
				return this._Camera;
			}
			set
			{
				if ((this._Camera != value))
				{
					this.OnCameraChanging(value);
					this.SendPropertyChanging();
					this._Camera = value;
					this.SendPropertyChanged("Camera");
					this.OnCameraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RAM", DbType="NVarChar(20)")]
		public string RAM
		{
			get
			{
				return this._RAM;
			}
			set
			{
				if ((this._RAM != value))
				{
					this.OnRAMChanging(value);
					this.SendPropertyChanging();
					this._RAM = value;
					this.SendPropertyChanged("RAM");
					this.OnRAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Battery", DbType="NVarChar(20)")]
		public string Battery
		{
			get
			{
				return this._Battery;
			}
			set
			{
				if ((this._Battery != value))
				{
					this.OnBatteryChanging(value);
					this.SendPropertyChanging();
					this._Battery = value;
					this.SendPropertyChanged("Battery");
					this.OnBatteryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int")]
		public System.Nullable<int> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageName", DbType="NVarChar(30)")]
		public string ImageName
		{
			get
			{
				return this._ImageName;
			}
			set
			{
				if ((this._ImageName != value))
				{
					this.OnImageNameChanging(value);
					this.SendPropertyChanging();
					this._ImageName = value;
					this.SendPropertyChanged("ImageName");
					this.OnImageNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
